strangeError_inResult
7 in dialects
adding names for rubric=LTER
Traceback (most recent call last):
  File "./scripts/generateSS.py", line 267, in <module>
    add_formulas()
  File "./scripts/generateSS.py", line 199, in add_formulas

add_named_ranges(start_row+1,end_row,dialectCount,existsCount,key,wb,
sheetRows, sheet, spiralCount)
  File "./py/ssutils.py", line 222, in add_named_ranges
    rnge =
"="+simplify(rubric)+"!$"+lastPercentCol+"$"+str(dialectRowStart)+":$"+l
astPercentCol+"$"+str(dialectRowEnd)
TypeError: cannot concatenate 'str' and 'int' objects
Exception Exception: Exception('Exception caught in workbook
destructor. Explicit close() may be required for workbook.',) in <bound
method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at
0x103053890>> ignored